Unit CargarFixture;

Interface

    Const
        MAX_PARTIDOS = 26;

    Type

        tFechaFixture = record 
                            dia, mes, hora, minutos : byte;
                            numero_partido: byte;
                            instancia, local, visitante : string;
                        end;

        tFixture = array [1..MAX_PARTIDOS] of tFechaFixture;

    { PRE: No hay precondiciones
      POS: El procedimiento cargar_fixture retorna el fixture del 
           torneo en el par metro formal llamado fixture.
    }
    procedure cargar_fixture(var fixture: tFixture);

Implementation

    procedure cargar_fixture(var fixture: tFixture);
    begin
        fixture[1].dia := 11;
        fixture[1].mes := 6;
        fixture[1].hora := 18;
        fixture[1].minutos := 30;
        fixture[1].numero_partido := 1;
        fixture[1].instancia := 'Grupo';
        fixture[1].local := 'Chile';
        fixture[1].visitante := 'Ecuador';
        fixture[2].dia := 12;
        fixture[2].mes := 6;
        fixture[2].hora := 18;
        fixture[2].minutos := 30;
        fixture[2].numero_partido := 2;
        fixture[2].instancia := 'Grupo';
        fixture[2].local := 'M‚xico';
        fixture[2].visitante := 'Bolivia';
        fixture[3].dia := 13;
        fixture[3].mes := 6;
        fixture[3].hora := 14;
        fixture[3].minutos := 0;
        fixture[3].numero_partido := 3;
        fixture[3].instancia := 'Grupo';
        fixture[3].local := 'Uruguay';
        fixture[3].visitante := 'Jamaica';
        fixture[4].dia := 13;
        fixture[4].mes := 6;
        fixture[4].hora := 16;
        fixture[4].minutos := 30;
        fixture[4].numero_partido := 4;
        fixture[4].instancia := 'Grupo';
        fixture[4].local := 'Argentina';
        fixture[4].visitante := 'Paraguay';
        fixture[5].dia := 14;
        fixture[5].mes := 6;
        fixture[5].hora := 14;
        fixture[5].minutos := 0;
        fixture[5].numero_partido := 5;
        fixture[5].instancia := 'Grupo';
        fixture[5].local := 'Colombia';
        fixture[5].visitante := 'Venezuela';
        fixture[6].dia := 14;
        fixture[6].mes := 6;
        fixture[6].hora := 16;
        fixture[6].minutos := 30;
        fixture[6].numero_partido := 6;
        fixture[6].instancia := 'Grupo';
        fixture[6].local := 'Brasil';
        fixture[6].visitante := 'Per£';
        fixture[7].dia := 15;
        fixture[7].mes := 6;
        fixture[7].hora := 16;
        fixture[7].minutos := 0;
        fixture[7].numero_partido := 7;
        fixture[7].instancia := 'Grupo';
        fixture[7].local := 'Ecuador';
        fixture[7].visitante := 'Bolivia';
        fixture[8].dia := 15;
        fixture[8].mes := 6;
        fixture[8].hora := 18;
        fixture[8].minutos := 30;
        fixture[8].numero_partido := 8;
        fixture[8].instancia := 'Grupo';
        fixture[8].local := 'Chile';
        fixture[8].visitante := 'M‚xico';
        fixture[9].dia := 16;
        fixture[9].mes := 6;
        fixture[9].hora := 16;
        fixture[9].minutos := 0;
        fixture[9].numero_partido := 9;
        fixture[9].instancia := 'Grupo';
        fixture[9].local := 'Paraguay';
        fixture[9].visitante := 'Jamaica';
        fixture[10].dia := 16;
        fixture[10].mes := 6;
        fixture[10].hora := 18;
        fixture[10].minutos := 30;
        fixture[10].numero_partido := 10;
        fixture[10].instancia := 'Grupo';
        fixture[10].local := 'Argentina';
        fixture[10].visitante := 'Uruguay';
        fixture[11].dia := 17;
        fixture[11].mes := 6;
        fixture[11].hora := 18;
        fixture[11].minutos := 30;
        fixture[11].numero_partido := 11;
        fixture[11].instancia := 'Grupo';
        fixture[11].local := 'Brasil';
        fixture[11].visitante := 'Colombia';
        fixture[12].dia := 18;
        fixture[12].mes := 6;
        fixture[12].hora := 18;
        fixture[12].minutos := 30;
        fixture[12].numero_partido := 12;
        fixture[12].instancia := 'Grupo';
        fixture[12].local := 'Per£';
        fixture[12].visitante := 'Venezuela';
        fixture[13].dia := 19;
        fixture[13].mes := 6;
        fixture[13].hora := 16;
        fixture[13].minutos := 0;
        fixture[13].numero_partido := 13;
        fixture[13].instancia := 'Grupo';
        fixture[13].local := 'M‚xico';
        fixture[13].visitante := 'Ecuador';
        fixture[14].dia := 19;
        fixture[14].mes := 6;
        fixture[14].hora := 18;
        fixture[14].minutos := 30;
        fixture[14].numero_partido := 14;
        fixture[14].instancia := 'Grupo';
        fixture[14].local := 'Chile';
        fixture[14].visitante := 'Bolivia';
        fixture[15].dia := 20;
        fixture[15].mes := 6;
        fixture[15].hora := 14;
        fixture[15].minutos := 0;
        fixture[15].numero_partido := 15;
        fixture[15].instancia := 'Grupo';
        fixture[15].local := 'Uruguay';
        fixture[15].visitante := 'Paraguay';
        fixture[16].dia := 20;
        fixture[16].mes := 6;
        fixture[16].hora := 16;
        fixture[16].minutos := 30;
        fixture[16].numero_partido := 16;
        fixture[16].instancia := 'Grupo';
        fixture[16].local := 'Argentina';
        fixture[16].visitante := 'Jamaica';
        fixture[17].dia := 21;
        fixture[17].mes := 6;
        fixture[17].hora := 14;
        fixture[17].minutos := 0;
        fixture[17].numero_partido := 17;
        fixture[17].instancia := 'Grupo';
        fixture[17].local := 'Colombia';
        fixture[17].visitante := 'Per£';
        fixture[18].dia := 21;
        fixture[18].mes := 6;
        fixture[18].hora := 16;
        fixture[18].minutos := 30;
        fixture[18].numero_partido := 18;
        fixture[18].instancia := 'Grupo';
        fixture[18].local := 'Brasil';
        fixture[18].visitante := 'Venezuela';
        fixture[19].dia := 24;
        fixture[19].mes := 6;
        fixture[19].hora := 18;
        fixture[19].minutos := 30;
        fixture[19].numero_partido := 19;
        fixture[19].instancia := 'Cuartos de final';
        fixture[19].local := '1A';
        fixture[19].visitante := '1M3';
        fixture[20].dia := 25;
        fixture[20].mes := 6;
        fixture[20].hora := 18;
        fixture[20].minutos := 30;
        fixture[20].numero_partido := 20;
        fixture[20].instancia := 'Cuartos de final';
        fixture[20].local := '2A';
        fixture[20].visitante := '2C';
        fixture[21].dia := 26;
        fixture[21].mes := 6;
        fixture[21].hora := 18;
        fixture[21].minutos := 30;
        fixture[21].numero_partido := 21;
        fixture[21].instancia := 'Cuartos de final';
        fixture[21].local := '1B';
        fixture[21].visitante := '2M3';
        fixture[22].dia := 27;
        fixture[22].mes := 6;
        fixture[22].hora := 16;
        fixture[22].minutos := 30;
        fixture[22].numero_partido := 22;
        fixture[22].instancia := 'Cuartos de final';
        fixture[22].local := '1C';
        fixture[22].visitante := '2B';
        fixture[23].dia := 29;
        fixture[23].mes := 6;
        fixture[23].hora := 18;
        fixture[23].minutos := 30;
        fixture[23].numero_partido := 23;
        fixture[23].instancia := 'Semifinal';
        fixture[23].local := 'G19';
        fixture[23].visitante := 'G20';
        fixture[24].dia := 30;
        fixture[24].mes := 6;
        fixture[24].hora := 18;
        fixture[24].minutos := 30;
        fixture[24].numero_partido := 24;
        fixture[24].instancia := 'Semifinal';
        fixture[24].local := 'G21';
        fixture[24].visitante := 'G22';
        fixture[25].dia := 3;
        fixture[25].mes := 7;
        fixture[25].hora := 18;
        fixture[25].minutos := 30;
        fixture[25].numero_partido := 25;
        fixture[25].instancia := 'Tercer y Cuarto puesto';
        fixture[25].local := 'P23';
        fixture[25].visitante := 'P24';
        fixture[26].dia := 4;
        fixture[26].mes := 7;
        fixture[26].hora := 15;
        fixture[26].minutos := 0;
        fixture[26].numero_partido := 26;
        fixture[26].instancia := 'Final';
        fixture[26].local := 'G23';
        fixture[26].visitante := 'G24';
    end;

End.
